version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
jobs:
  e2e_env:
    working_directory: ~/umaverse
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: Start local test network
          command: |
            make create-e2e-network
      - run:
          name: Start local fork node
          command: |
            make node-local
      - run:
          name: Check local node status
          command: |
            make node-status
      - run:
          name: Start local API
          command: |
            make api-local
      - run:
          name: Install dependencies
          command: |
            make e2e-dependencies
      - run:
          name: Check local api status
          command: |
            make api-status
      - run:
          name: Execute e2e tests
          command: |
            make e2e-tests

workflows:
  version: 2.1
  e2e_tests:
    jobs:
      - e2e_env:
          context:
            - umaverse
