version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
jobs:
  e2e_env:
    working_directory: ~/umaverse
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Start local test environment
          command: |
            make local-node
            make local-api
      - run:
          name: Install dependencies
          command: |
            npm install
            npm run build
      - run:
          name: Execute e2e tests
          command: |
            make e2e-tests


workflows:
  version: 2.1
  e2e_tests:
    jobs:
      - e2e_env:
          context:
            - umaverse
