version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
jobs:
  e2e_env:
    working_directory: ~/umaverse
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Start local test environment
          command: |
            make node-local
            make api-local
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Check local api status
          command: |
            make api-status
      - run:
          name: Execute e2e tests
          command: |
            ./check_api_status.sh
            make e2e-tests


workflows:
  version: 2.1
  e2e_tests:
    jobs:
      - e2e_env:
          context:
            - umaverse
