version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: trufflesuite/ganache-cli
        command: npx hardhat node --fork $NODE_URL
    working_directory: ~/umaverse
    resource_class: medium+
    steps:
      - run:
          name: Execute tests
          command: |
            echo "bootstrap CI"
