version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
jobs:
  build:
    docker:
      - image: cypress/base:14.17.0
      - image: trufflesuite/ganache-cli
#Personal infura test key for testing
        command: ganache-cli --fork wss://mainnet.infura.io/ws/v3/aacab9aa428048fe8426c1c0c64f182f
      - image: gcr.io/uma-protocol/github.com/umaprotocol/protocol:latest
        environment:
#Personal infura test key for testing
          CUSTOM_NODE_URL: wss://mainnet.infura.io/ws/v3/aacab9aa428048fe8426c1c0c64f182f
          EXPRESS_PORT: $EXPRESS_PORT
        command: sh -c env
    working_directory: ~/umaverse
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: test
          command: echo ${TEST_VAR}
      - run:
          name: Install dependencies
          command: |
            yarn install
      - run:
          name: Execute tests
          command: |
            cypress run


# workflows:
#   version: 2.1
#   e2e_tests:
#     jobs:
#       - build
#       - cypress/run:
#           requires:
#             - build
